import { existsSync } from "node:fs";
import { join } from "node:path";
import { config } from "./config.ts";
import { catalog } from "./models-catalog.ts";
import type { StarterModel, StarterModelState } from "@latent/shared";

/**
 * Curated first-run model set. The Illustrious side is a "choose your house style"
 * checkpoint menu (grouped by category) plus checkpoint-agnostic support models; the
 * WAN side is what the video pipeline needs. `recommended` marks the suggested pick.
 * Checkpoints resolved to their latest Civitai version + primary file (mid-2026).
 */
export const STARTER_MODELS: StarterModel[] = [
  // ── Illustrious checkpoints — choose your style ─────────────────────────────
  {
    id: "wai",
    label: "WAI-illustrious-SDXL",
    description: "The default pick — most-downloaded Illustrious model, largest LoRA ecosystem.",
    pack: "illustrious",
    category: "Anime — all-rounders",
    recommended: true,
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "waiIllustriousSDXL_v170.safetensors",
    sizeBytes: 6938427392,
    nsfw: true,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/bf704a4b-9e7c-4651-9387-91f121b24ef3/original=true/128374653.jpeg",
    source: { type: "civitai", modelId: 827184, versionId: 2883731 },
  },
  {
    id: "ntrmix",
    label: "NTR MIX",
    description: "NoobAI-merged; punchier, darker rendering with strong anatomy.",
    pack: "illustrious",
    category: "Anime — all-rounders",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "ntrMIXIllustriousXL_xiii.safetensors",
    sizeBytes: 6938427392,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/32f84039-2e6c-4ef0-b714-b4f13684649e/original=true/45654541.jpeg",
    source: { type: "civitai", modelId: 926443, versionId: 1166878 },
  },
  {
    id: "ilustmix",
    label: "iLustMix",
    description: "Clean, vibrant, very responsive to aesthetic tags.",
    pack: "illustrious",
    category: "Anime — all-rounders",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "ilustmix_v111.safetensors",
    sizeBytes: 7105150976,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/b294d804-d679-4666-8f05-f0a4900ae067/original=true/125529427.jpeg",
    source: { type: "civitai", modelId: 1110783, versionId: 2807896 },
  },
  {
    id: "amix",
    label: "A-mix",
    description: "Reliable hentai/anime merge for solo character work.",
    pack: "illustrious",
    category: "Anime — all-rounders",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "aMixIllustrious_aMix.safetensors",
    sizeBytes: 7105150976,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/be363071-0c5f-4235-88b5-47e27740e298/original=true/82973996.jpeg",
    source: { type: "civitai", modelId: 1692152, versionId: 1915059 },
  },
  {
    id: "hassaku",
    label: "Hassaku XL",
    description: "Strong all-round anime NSFW model.",
    pack: "illustrious",
    category: "Anime — all-rounders",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "hassakuXLIllustrious_v34.safetensors",
    sizeBytes: 6938427392,
    nsfw: true,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/ea4c627d-91f2-486a-bc8f-026d316684e2/original=true/118186280.jpeg",
    source: { type: "civitai", modelId: 140272, versionId: 2615702 },
  },
  {
    id: "illustrij",
    label: "Illustrij",
    description: "Flat-anime faces with subtle 3D lighting — the '2.5D' look.",
    pack: "illustrious",
    category: "Semi-real (2.5D)",
    recommended: true,
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "illustrij_v21.safetensors",
    sizeBytes: 7419723776,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/36e64e8d-4951-4a04-a726-e5733d9d7c17/original=true/125793811.jpeg",
    source: { type: "civitai", modelId: 1025051, versionId: 2728617 },
  },
  {
    id: "semireal-mm",
    label: "Semi-Real",
    description: "Leans toward realistic rendering while keeping tag prompting.",
    pack: "illustrious",
    category: "Semi-real (2.5D)",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "semiRealIllustrious_v30.safetensors",
    sizeBytes: 6938427392,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/d662bc4d-57b1-4e1d-94da-b232c7b23f50/original=true/134458460.jpeg",
    source: { type: "civitai", modelId: 1945811, versionId: 3057034 },
  },
  {
    id: "realism-yogi",
    label: "Realism Illustrious By Stable Yogi",
    description: "The main Illustrious realism pick; ships its own embeddings.",
    pack: "illustrious",
    category: "Realism",
    recommended: true,
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "realismIllustriousBy_v55FP16.safetensors",
    sizeBytes: 6938427392,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/0e6e6378-07b9-4454-bcf9-f920fc0085d5/original=true/126483436.jpeg",
    source: { type: "civitai", modelId: 974693, versionId: 2831949 },
  },
  {
    id: "nova-furry",
    label: "Nova Furry XL",
    description: "The furry all-rounder — great fur/scale/feather detail, e621-native.",
    pack: "illustrious",
    category: "Furry — 2D / cartoon",
    recommended: true,
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "novaFurryXL_ilV180A.safetensors",
    sizeBytes: 6939475968,
    nsfw: true,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/4c9f5e9f-db99-461c-8c7e-645439bdfbea/original=true/130620207.jpeg",
    source: { type: "civitai", modelId: 503815, versionId: 2943166 },
  },
  {
    id: "furrytoonmix",
    label: "FurryToonMix",
    description: "Western/cartoon, cute and rounded, broad species coverage.",
    pack: "illustrious",
    category: "Furry — 2D / cartoon",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "furrytoonmix_xlV3.safetensors",
    sizeBytes: 7105150976,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/2a6c9402-b4fb-483d-9ebd-a54fa496e187/original=true/131291614.jpeg",
    source: { type: "civitai", modelId: 97479, versionId: 2961728 },
  },
  {
    id: "uwumerge",
    label: "uwumerge",
    description: "Strong outlines and saturated colors; stylized.",
    pack: "illustrious",
    category: "Furry — 2D / cartoon",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "uwumergeFurry_v60CKXL.safetensors",
    sizeBytes: 6938427392,
    nsfw: true,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/73e9ee2e-40b5-4c8b-881c-8336345ca591/original=true/130616116.jpeg",
    source: { type: "civitai", modelId: 2368916, versionId: 2941682 },
  },
  {
    id: "anthroblend",
    label: "AnthroBlend - Indigo Genesis",
    description: "Clean cel-shaded, smooth colors; handles humans too.",
    pack: "illustrious",
    category: "Furry — 2D / cartoon",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "anthroblendIndigo_v30.safetensors",
    sizeBytes: 6938427392,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/5464b873-5179-4f55-9e99-6b6a2324fb15/original=true/132803564.jpeg",
    source: { type: "civitai", modelId: 2432781, versionId: 3004444 },
  },
  {
    id: "oops-furries",
    label: "Oops! All Furries",
    description: "Versatile furry merge that also does non-furry; e621 + Danbooru tags.",
    pack: "illustrious",
    category: "Furry — 2D / cartoon",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "oopsAllFurries_v2.safetensors",
    sizeBytes: 7105150976,
    nsfw: true,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/265b3935-5ef8-4122-90f6-ecae4637a73b/original=true/60061723.jpeg",
    source: { type: "civitai", modelId: 1273028, versionId: 1461295 },
  },
  {
    id: "yiff-in-hell",
    label: "Yiff in Hell — VANTABLACK",
    description: "Dark, high-contrast furry model (the original bundled pick).",
    pack: "illustrious",
    category: "Furry — 2D / cartoon",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "yiffInHell_yihVANTABLACK.safetensors",
    nsfw: true,
    source: { type: "civitai", modelId: 1570986, versionId: 2701283 },
  },
  {
    id: "nova-animal",
    label: "Nova Animal XL",
    description: "Nova's realistic sibling — controlled fur, photoreal lean.",
    pack: "illustrious",
    category: "Furry — realistic",
    recommended: true,
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "novaAnimalXL_ilV120.safetensors",
    sizeBytes: 6939475968,
    nsfw: true,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/f7d448f7-a95c-4170-93aa-acd1c9e7fa11/original=true/125808054.jpeg",
    source: { type: "civitai", modelId: 784543, versionId: 2814977 },
  },
  {
    id: "purrfection",
    label: "Purrfection",
    description: "Cinematic, well-lit photoreal furry.",
    pack: "illustrious",
    category: "Furry — realistic",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "purrfectionFurryRealisticILXL_v10.safetensors",
    sizeBytes: 6938427392,
    nsfw: true,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/702e46e2-eb79-4a51-bf6b-047221f5932f/original=true/72259905.jpeg",
    source: { type: "civitai", modelId: 1509216, versionId: 1707179 },
  },
  {
    id: "kft-requiem",
    label: "KFT Requiem Fur a Dream",
    description: "Semi-real furry; stacks nicely with style LoRAs.",
    pack: "illustrious",
    category: "Furry — realistic",
    kind: "checkpoint",
    folder: "StableDiffusion",
    filename: "kftRequiemFurADream_v5vae.safetensors",
    sizeBytes: 7105150976,
    nsfw: true,
    previewUrl: "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/a17136f1-7a2f-4cf5-a68e-ee60d7533e1a/original=true/123447200.jpeg",
    source: { type: "civitai", modelId: 1031130, versionId: 2752320 },
  },

  // ── Support & extras (checkpoint-agnostic — the pipeline needs the VAE + upscaler) ──
  {
    id: "sdxl-vae",
    label: "SDXL VAE",
    description: "Standard SDXL VAE — the pipeline's default.",
    pack: "illustrious",
    category: "Support & extras",
    recommended: true,
    kind: "vae",
    folder: "VAE",
    filename: "sdxlVAE.safetensors",
    sizeBytes: 334641164,
    source: { type: "url", url: "https://huggingface.co/stabilityai/sdxl-vae/resolve/main/sdxl_vae.safetensors" },
  },
  {
    id: "xinsir-union-promax",
    label: "ControlNet Union (ProMax)",
    description:
      "xinsir's all-in-one SDXL ControlNet — one model for canny, depth, pose, lineart, tile & more. Required to use the ControlNet panel.",
    pack: "illustrious",
    category: "Support & extras",
    recommended: true,
    kind: "controlnet",
    folder: "ControlNet",
    filename: "xinsir_union_sdxl_promax.safetensors",
    sizeBytes: 2513342408,
    source: {
      type: "url",
      url: "https://huggingface.co/xinsir/controlnet-union-sdxl-1.0/resolve/main/diffusion_pytorch_model_promax.safetensors",
    },
  },
  {
    id: "remacri-4x",
    label: "4x Foolhardy Remacri",
    description: "Upscaler used by the pipeline's hires fix.",
    pack: "illustrious",
    category: "Support & extras",
    recommended: true,
    kind: "upscale",
    folder: "ESRGAN",
    filename: "4x_foolhardy_Remacri.pth",
    sizeBytes: 67025055,
    source: { type: "url", url: "https://huggingface.co/uwg/upscaler/resolve/main/ESRGAN/4x_foolhardy_Remacri.pth" },
  },
  {
    id: "ultrasharp-4x",
    label: "4x UltraSharp",
    description: "Sharper alternative upscaler for hires fix.",
    pack: "illustrious",
    category: "Support & extras",
    kind: "upscale",
    folder: "ESRGAN",
    filename: "4x-UltraSharp.pth",
    sizeBytes: 66961958,
    source: { type: "url", url: "https://huggingface.co/Kim2091/UltraSharp/resolve/main/4x-UltraSharp.pth" },
  },
  {
    id: "smooth-quality",
    label: "Smooth — Quality (positive)",
    description: "Quality-boost embedding for Illustrious.",
    pack: "illustrious",
    category: "Support & extras",
    kind: "embedding",
    folder: "Embeddings",
    filename: "Smooth_Quality.safetensors",
    source: { type: "civitai", modelId: 1065154, versionId: 1470551 },
  },
  {
    id: "smooth-negative",
    label: "Smooth — Negative",
    description: "Negative-prompt embedding for Illustrious.",
    pack: "illustrious",
    category: "Support & extras",
    kind: "embedding",
    folder: "Embeddings",
    filename: "Smooth_Negative-neg.safetensors",
    source: { type: "civitai", modelId: 1065154, versionId: 1195487 },
  },
  {
    id: "smooth-negative-hands",
    label: "Smooth — Negative Hands",
    description: "Hand-fixing negative embedding.",
    pack: "illustrious",
    category: "Support & extras",
    kind: "embedding",
    folder: "Embeddings",
    filename: "SmoothNegative_Hands-neg.safetensors",
    source: { type: "civitai", modelId: 1065154, versionId: 1668031 },
  },
  {
    id: "face-yolov8m",
    label: "Face detector (yolov8m)",
    description: "For the pipeline's face-detailer step.",
    pack: "illustrious",
    category: "Support & extras",
    recommended: true,
    folder: "Ultralytics/bbox",
    filename: "face_yolov8m.pt",
    sizeBytes: 52026019,
    source: { type: "url", url: "https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8m.pt" },
  },
  {
    id: "hand-yolov8s",
    label: "Hand detector (yolov8s)",
    description: "Detail-fix hands with ADetailer.",
    pack: "illustrious",
    category: "Support & extras",
    folder: "Ultralytics/bbox",
    filename: "hand_yolov8s.pt",
    sizeBytes: 22507421,
    source: { type: "url", url: "https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8s.pt" },
  },
  {
    id: "person-yolov8m-seg",
    label: "Person segmenter (yolov8m-seg)",
    description: "Segmentation model for whole-person ADetailer.",
    pack: "illustrious",
    category: "Support & extras",
    folder: "Ultralytics/segm",
    filename: "person_yolov8m-seg.pt",
    sizeBytes: 54809683,
    source: { type: "url", url: "https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8m-seg.pt" },
  },

  // ── WAN 2.2 (video) ────────────────────────────────────────────────────────
  {
    id: "wan-unet-high",
    label: "DaSiWa WAN 2.2 — High (GGUF)",
    description: "High-noise I2V UNet (GGUF). Large ~several GB.",
    pack: "wan",
    category: "WAN 2.2 video",
    recommended: true,
    kind: "diffusion",
    folder: "DiffusionModels",
    filename: "DasiwaWAN22I2V14BLightspeed_snatchkissHighV11.gguf",
    nsfw: true,
    source: { type: "civitai", modelId: 2633067, versionId: 2956320 },
  },
  {
    id: "wan-unet-low",
    label: "DaSiWa WAN 2.2 — Low (GGUF)",
    description: "Low-noise I2V UNet (GGUF). Pairs with the High unet.",
    pack: "wan",
    category: "WAN 2.2 video",
    recommended: true,
    kind: "diffusion",
    folder: "DiffusionModels",
    filename: "DasiwaWAN22I2V14BLightspeed_snatchkissLowV11.gguf",
    nsfw: true,
    source: { type: "civitai", modelId: 2633067, versionId: 2957206 },
  },
  {
    id: "wan-text-encoder",
    label: "WAN text encoder (umt5-xxl)",
    description: "The umt5-xxl text encoder the WAN pipeline's CLIPLoader needs.",
    pack: "wan",
    category: "WAN 2.2 video",
    recommended: true,
    folder: "TextEncoders",
    filename: "umt5_xxl_fp8_e4m3fn_scaled.safetensors",
    source: {
      type: "url",
      url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/text_encoders/umt5_xxl_fp8_e4m3fn_scaled.safetensors",
    },
  },
  {
    id: "wan-vae",
    label: "WAN 2.1 VAE",
    description: "The WAN video VAE (lands in VAE/Wan).",
    pack: "wan",
    category: "WAN 2.2 video",
    recommended: true,
    kind: "vae",
    folder: "VAE/Wan",
    filename: "wan_2.1_vae.safetensors",
    source: {
      type: "url",
      url: "https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/vae/wan_2.1_vae.safetensors",
    },
  },
  {
    id: "rife-4.26",
    label: "RIFE v4.26 (frame interpolation)",
    description: "Optional interpolation model for smoother video (~23 MB).",
    pack: "wan",
    category: "WAN 2.2 video — optional",
    folder: "frame_interpolation",
    filename: "rife_v4.26.safetensors",
    sizeBytes: 23_800_000,
    source: {
      type: "url",
      url: "https://huggingface.co/Comfy-Org/frame_interpolation/resolve/main/frame_interpolation/rife_v4.26.safetensors",
    },
  },
];

/** Is a starter model already present on disk? */
function isInstalled(m: StarterModel): boolean {
  if (m.kind) return !!catalog.get(m.kind, m.filename); // catalog keys by relative filename
  return existsSync(join(config.smModelsDir, m.folder, m.filename));
}

/** Registry annotated with local install state. */
export function starterModelsWithState(): StarterModelState[] {
  return STARTER_MODELS.map((m) => ({ ...m, installed: isInstalled(m) }));
}
